### PR TITLE
Merge to master PR

### PR DESCRIPTION
**Pull request by ansaryergesh**

### CODE REVIEW

**Comment by maelfosso** [comment]
Hello,

- [x] Update your README. Add a description, the author's names with link to their Github profile and a link to the live version of the project.

- [x] Correct errors from https://validator.w3.org

- [x] The search icon should be inside a button.

- [x] Like, Dislike and Share, all are buttons. 

- [x] **Subscribe** is a button

Please, kindly make those changes and submit a new code review request.

**Comment by jofer86** [comment]
Hello guys, good work on fixing those problems!!! I have a couple of concerns though number one, as I can see from your commits that this particular project was made only by one person, could you please explain to me if there was an issue that could be brought to our attention so that we can work something out?. Please let me know what happened, and kindly resubmit. There is also an issue when the screen when is not that wide, you get a scroll bar, ideally, you would want to fix those, but that is beyond the scope of this project. Please let me know what happened with your partner and then we will be good to go. : :man_dancing: :wave:

**Comment by ansaryergesh** [comment]
Hello Jofer! thank you for your review. I finished that project with my
partner.everything is fine with my partner. But there is one thing .
firstly we did  in one repository 3 different projects and we worked only
with master branch. In addition we forgot to create pull request for the
project and we just sent the link of repository.  Then we get some review
from TSE. that we need to correct that errors. mentor is helped me to fix
that errors. Mentor is explained me everything then in collabiration work i
explained  to my coding partner all of that.(how to work with branches) But
we work together i can send you another link for that. To fix the errors I
just copied everything from project that we've done together. you can see
it from that link  there is another commits:
https://github.com/ansaryergesh/the_odin_project/tree/master/youtube_page

сб, 13 июл. 2019 г. в 09:46, jofer86 <notifications@github.com>:

**Comment by jofer86** [comment]
:+1: :+1: That's thumbs up from me you can now merge to master!. I strongly suggest, from now on to always make sure you don't get a horizontal scrollbar, unless it is intentional or pertinent for the site in question, in this case the culprit is the class with the name of row, which is set to be 140rem wide, that caused the overflow, sometimes it might be hard to get everything to fit, but it is doable if u work some magic here and there. Anyways, good job, have a nice weekend. Also, I'm available on Slack, if you come across an issue I would gladly help.

**Comment by ansaryergesh** [comment]
OK, got it. Thank you so much! We will try to avoid such errors. Have a
nice weekend too👍

сб, 13 июл. 2019 г. в 17:57, jofer86 <notifications@github.com>:

**Pull request merged**
